# Generated by Django 5.1.3 on 2025-02-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_inital'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitie',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
